### ISSUE TITLE
Please stop depending on colorize

### ISSUE THREAD

**Issue by solnic** [phrase/phrase#47]
Colorize gem monkey-patches `String` and it's not nice. There are alternatives to this gem that don't do that like [hansi](https://github.com/rkh/hansi) or [rainbow](https://github.com/sickill/rainbow).

**Comment by docstun** [comment]
Valid point, anyone of you (@solnic, @sickill) able to provide a quick PR?

**Comment by docstun** [comment]
Should be fine in master now

**Comment by solnic** [comment]
Awesome thanks :)
