### ISSUE TITLE
Gettext with inline translate tool

### ISSUE THREAD

**Issue by jarosan** [phrase/phrase#51]
Hi,

We are trying to integrate phrase app with gettext into our website and we ran into several problems.

First one (major one) is that it seems that your inline javascript cannot map gettext keys to translated keys and all keys appear untranslated.

The second one is that if a key contains characters like ```ä```, ```ö``` or ```´``` then the key is not processed and appears like ```{{__phrase_Stelle Fragen oder hilf anderen dabei Probleme zu lösen @cover__}}``` on the web page.

Cheers,

Jaroslav.

**Comment by docstun** [comment]
Did you try to set autoLowercase to false? Should at least fix your first issue:

http://docs.phraseapp.com/guides/in-context-editor/configure/

**Comment by jarosan** [comment]
Setting autoLowercase to false indeed fixed the first issue. Thanks. Second one is still present however.

Also if i try to set in the initializer
```
  Phrase.configure do |config|
    # Enable or disable the PhraseApp context editor in general
    config.enabled = false
  end
```
Instead of normal looking keys i get ```{{__phrase_Welcome to Community @cover__}}```. What am I doing wrong here?

**Comment by docstun** [comment]
Did you restart the rails app server after changing the configuration?
You always need to restart the app when changing an initializer.

**Comment by jarosan** [comment]
I know and i did. I am including the gem in an engine. Maybe this has something to do with this?

**Comment by docstun** [comment]
I guess the loading order might be an issue here. We'll take a look at this soon. Could you explain which engine you're using?

Regarding your issue from earlier: We'll update the In-Context-Editor parser hopefully next week so that umlauts and other chars won't be an issue any longer. What other chars did cause problems in your setup?

**Comment by jarosan** [comment]
Our main app is built as a rails engine gem, that other apps can include.

**Comment by docstun** [comment]
@jarosan we have updated the In-Context-Editor parser to support umlauts and accents as well, it will be available in the next update. We're further investigating the issue with your Rails Engine.

**Comment by docstun** [comment]
@jarosan we've added a fix to master that might solve your problem. Could you check if this solves it for you?
