### ISSUE TITLE
Phrase works on entire application not for single user

### ISSUE THREAD

**Issue by jjustaments** [phrase/phrase#52]
We use phrase in multi-user environment so each user can turn on or off without affecting other users. Phrase.enabled switch works on entire application and we made patch for our needs.

```
# PATCH: store enabled switch value as instance variable and class variable use only for first time initialization with config value
#        it will allow correctly work phrase in multi user environment
class Phrase::Config
  def enabled
    # @@enabled = false if !defined? @@enabled or @@enabled.nil?
    # @@enabled
    @enabled = @@enabled if !defined?(@enabled) && defined?(@@enabled)
    @enabled = false if @enabled.nil?
    @enabled
  end

  def enabled=(enabled)
    # @@enabled = enabled
    @@enabled = enabled if !defined? @@enabled
    @enabled = enabled
  end
end
```

**Comment by docstun** [comment]
I am not sure I'm following you. Whenever you have multiple processes or threads the configuration might fail so the translator possibly won't have the editor enabled when expected, isn't that right?

**Comment by jjustaments** [comment]
We set Phrase.enable value on every request in before_filter.

**Comment by jjustaments** [comment]
I will close the issue as this is not a bug. 
This is the new use case of using PhraseApp, it could be great feature
