### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by nTraum** [phrase/phrase#56]
Hi phrase team,

have you thought about adding a changelog for this gem? It really helps spotting breaking changes / new features when updating to newer versions.

http://keepachangelog.com/ gives a good starting point on how such changelog could look like in my opinion.

**Comment by docstun** [comment]
Thanks, we'll add this for our new gem(s) that will be released soon!

**Comment by nTraum** [comment]
Thanks a lot! :)
