### ISSUE TITLE
THIS GEM IS DEPRECATED

### ISSUE THREAD

**Issue by fluxsaas** [phrase/phrase#59]
the documentation still refers to this gem:

https://phraseapp.com/docs/guides/setup/localize-ruby-on-rails-applications-with-phraseapp/

what now?

**Comment by docstun** [comment]
You're right, this article is outdated. Somehow the link is not correct, this is the one you're looking for: https://phraseapp.com/docs/guides/setup/ruby-on-rails/

See this article for information how to add the In-Context editor to a Rails app: https://phraseapp.com/docs/guides/in-context-editor/setup/

I will make sure the outdated article is deleted.

Thanks!
